name: Build & Test

on:
  push:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build-and-test.yml"
      - ".vscode/**"
      - "doc/**"
      - "lifecycle/**"
      - ".gitignore"
      - "README.md"
  pull_request:

jobs:
  i18n:
    name: Generate i18n catalog
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      committed: ${{ steps.commit.outputs.committed }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise install:frozen
      - run: mise build:deps
      - run: mise lingui

      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Stoat CI
          author_email: stoat-ci@users.noreply.github.com
          message: "chore: generate i18n catalog"

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    if: needs.i18n.outputs.committed != 'true'
    needs:
      - i18n

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise install:frozen
      - run: mise build:deps
      - run: mise build:check

  lint-format:
    name: Lint & Format
    runs-on: ubuntu-latest

    if: needs.i18n.outputs.committed != 'true'
    needs:
      - i18n

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise install:frozen
      - run: mise build:deps
      - run: mise lint
      - run: mise format

  e2e:
    name: e2e Integration Test
    runs-on: ubuntu-latest

    if: needs.i18n.outputs.committed != 'true'
    needs:
      - i18n

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@cd24790a7f5f6439ac32cc94f5523cb2de8bfa8c # use-mise-action-v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise install:frozen
      - run: mise build:deps
      - run: mise test:e2e:install-deps
      - run: mise test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/client/playwright-report/
          retention-days: 30

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: write

  #   if: github.ref == 'refs/heads/main'

  #   needs:
  #     - typecheck
  #     - e2e
  #     - lint-format

  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - run: |
  #         git fetch origin stable:stable
  #         git push origin main:stable -f
